### PR TITLE
.

### PR DESCRIPTION
**Pull request by ghost**
.

### CODE REVIEW

**Review by michaelbaudino — APPROVED** [review]
Gotcha :+1:

**Comment by michaelbaudino** [comment]
Hrm, maybe this should be added to [docs/rails.md](https://github.com/alpinelab/codestyle/blob/master/docs/rails.md), @tjouan ?

**Comment by tjouan** [comment]
@michaelbaudino I don't think we should document Rails own conventions because
it's a lot of work and it might not be correct or would become outdated easily.
IMO we should only document when we follow *different* conventions than Rails,
or if it's our own convention, independent from Rails.

For example about this specific one, here is the content of the generated `Rakefile`:
``` ruby
$ cat Rakefile 
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks
```

And from the guides:
https://guides.rubyonrails.org/command_line.html#custom-rake-tasks
> 2.9 Custom Rake Tasks
> 
> Custom rake tasks have a .rake extension and are placed in Rails.root/lib/tasks. You can create these custom rake tasks with the bin/rails generate task command.

**Comment by michaelbaudino** [comment]
Alrighty :+1:

**Pull request merged**
