### PR TITLE
.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by michaelbaudino — APPROVED** [review]
Totally agree :+1: (who wouldn't ? :grimacing:)

**Comment by tjouan** [comment]
Ironically, the project where I was testing our rules didn't trigger this
offense at first. But I had to change this code:
``` ruby
  get "sitemap(.:format)", to: "sitemap#show", as: "sitemap",
    defaults: { format: :xml }
```
with one argument per line due to another rule, and it was enough to make the
block too big.

**Review by Polo2 — APPROVED** [review]
I agree too , of course

https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif

**Review by thibaultdalban — APPROVED** [review]
:ok:

**Pull request merged**
