### PR TITLE
Disable ABC Metrics

### PR DESCRIPTION
**Pull request by Polo2**
>This cop checks that the ABC size of methods is not higher than the configured maximum. The ABC >size is based on assignments, branches (method calls), and conditions. See http://c2.com/cgi/wiki?AbcMetric

it looks very constraignant.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
.

**Review by michaelbaudino — CHANGES_REQUESTED** [review]
I actually find this metric to be one of the most useful :heart_eyes: All the offenses I've seen being reported by it were legit (_i.e._ the method was difficult to understand).

**Comment by tjouan** [comment]
>  I also would like to test it again on a familiar code base before any change.

With version `~> 0.8`, I got those issues reported on a random project:
``` ruby
  def create
    respond_to do |format|
      format.js do
        build_resource(sign_up_params)
        resource.save
        if resource.persisted?
          render json: {
            success: true,
            message: t(
              "devise.registrations.signed_up_but_unconfirmed",
              user_mail: resource.email,
            ),
          },
          content_type: "application/json"
        else
          render json: { errors: resource.errors }, content_type: "application/json"
        end
      end
    end
  end
```
``` ruby
  def index
    @q = Resume.ransack(params_search)
    relation = @q.result.for_listing
    if params_postal_code_distance?
      relation = relation.postal_code_distance(
        params[:q][:contact_address_postal_code_cont],
        params[:postal_code_distance].to_i,
      )
    end
    @resumes = relation.page params[:page]
  end
```
``` ruby
  def call
    assign_attributes_from_author
    assign_attributes_from_params *%i[
      title body action
      from_firstname from_lastname from_mail from_phone
    ]
    message.user = User.find(params[:user_id]) if params.key? :user_id
    if params[:resume_id]
      message.resume = Resume.find(params[:resume_id])
      assign_attributes_from_params :rcpt_mail
      unless message.title || message.body
        message.body = resume_uri
        assign_attributes_for_review if message.review?
      end
    end
  end
```
``` ruby
  def normalize
    @params
      .merge(compact_values @params, :jobs)
      .merge(capacities @params)
      .merge(availability @params)
      .merge(select_any_value @params, :skills)
      .merge(select_any_value @params, :assets)
      .merge(experiences @params)
      .merge(select_any_value @params, :educations)
      .merge(select_any_value @params, :formations)
      .merge(select_any_value @params, :interests)
      .merge(compact_values @params, :pluses)
  end
```
``` ruby
  def call(params)
    @user = params.fetch :user
    @contact = @user.contact
    @from_mail = params.fetch :from_mail
    @from_firstname = params.fetch :from_firstname
    @from_lastname = params.fetch :from_lastname
    @from_phone = params.fetch :from_phone
    @title = params.fetch :title
    @body = params.fetch :body
    @host = Rails.application.secrets.host

    mail to: @user.email, subject: @title
  end
```

All of them were known as a bit too complex, so I think default configuration
isn't so bad, I'd keep default value of 15.

**Review by ghost — CHANGES_REQUESTED** [review]
.

**Comment by Polo2** [comment]
PR closed without being merged, 2 votes for it

**Pull request closed without merging**
