### PR TITLE
.

### PR DESCRIPTION
**Pull request by ghost**
.

### CODE REVIEW

**Review by michaelbaudino — CHANGES_REQUESTED** [review]
Hrm, I would actually force the use of parenthesis in this case. But I don't have any argument, it just feels like a personal preference in favour of expliciteness, tbh.

**Comment by tjouan** [comment]
My argument to forbid parenthesis is that I find it more readable and less
confusing in this case.

**Comment by thibaultdalban** [comment]
I vote to keep them.

**Review by thibaultdalban — CHANGES_REQUESTED** [review]
I vote to keep them.

**Review by Polo2 — CHANGES_REQUESTED** [review]
First team I've read 
```ruby
-> x, y { x + y }
```
I understood
```ruby
-> x, ( y { x + y } )
```
So I prefer with parentheses

**Pull request closed without merging**
